# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: OpenCode
version: "0.1.4"
slug: opencode
description: OpenCode web server for Home Assistant
url: "https://opencode.ai/"
startup: application
apparmor: false
hassio_api: true
homeassistant_api: true
hassio_role: admin
stage: experimental
arch:
    - aarch64
    - amd64
init: false
map:
    - config:rw
    - share:rw
ports:
    4096/tcp: 4096
ports_description:
    4096/tcp: OpenCode Web/API
webui: "http://[HOST]:[PORT:4096]"
ingress: true
ingress_port: 4096
panel_icon: mdi:alpha-o-box-outline
options:
    port: 4096
    username: "opencode"
    password: ""
    auto_update: false
schema:
    port: port
    username: str?
    password: password?
    auto_update: bool
image: "bradsjm/{arch}-addon-opencode"
