# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: OpenCode Server
version: "0.8"
slug: opencode
description: OpenCode web server configured for Home Assistant
url: "https://opencode.ai/"
startup: application
host_network: false
apparmor: false
hassio_api: true
homeassistant_api: true
hassio_role: manager
stage: experimental
arch:
    - aarch64
    - amd64
init: false
ingress: false
ingress_port: 0
ingress_stream: true
panel_icon: mdi:alpha-o-box
map:
    - config:rw
    - share:rw
ports:
    4096/tcp: 4096
ports_description:
    4096/tcp: OpenCode Web/API
webui: "http://[HOST]:[PORT:4096]"
options:
    port: 4096
    username: "opencode"
    password: ""
    opencode_version: ""
    opencode_env_vars: []
    packages: []
    init_commands: []
schema:
    port: port
    username: str?
    password: password?
    opencode_version: str?
    opencode_env_vars:
        - str
    packages:
        - str
    init_commands:
        - str
image: "bradsjm/{arch}-addon-opencode"
